from locust import HttpUser, between, task
import os
import random
import websocket
import time

class FastAPIUser(HttpUser):
    """Locust test class for the FastAPI application deployed on Render."""
    # wait time between tasks to simulate user think time
    wait_time = between(1, 3)
    host = "https://deployment-test-w2t8.onrender.com/"

    def on_start(self):
        # host is already set via class attribute; environment variable still works
        default_host = os.getenv("RENDER_EXTERNAL_URL", self.host)
        self.host = os.getenv("LOCUST_HOST", default_host)

    @task(1)
    def chat_ws(self):
        """Open a websocket, exchange a few messages, then close."""
        # convert http(s) to ws(s)
        url = self.host.rstrip("/").replace("http", "ws") + "/ws/chat"
        try:
            ws = websocket.create_connection(url, timeout=5)
            for i in range(3):
                msg = f"hello-{i}"
                ws.send(msg)
                # wait a moment to simulate user typing
                resp = ws.recv()
                time.sleep(0.1)
            ws.close()
        except Exception as e:
            # record as failure in locust statistics
            self.environment.events.request_failure.fire(
                request_type="WS",
                name="/ws/chat",
                response_time=0,
                exception=e,
            )

    @task(5)
    def home(self):
        self.client.get("/")

    @task(2)
    def health(self):
        self.client.get("/health")

    @task(3)
    def get_item(self):
        item_id = random.randint(1, 1000)
        self.client.get(f"/api/items/{item_id}")

    @task(2)
    def create_item(self):
        payload = {"name": f"item-{random.randint(1,10000)}", "description": "generated by locust"}
        self.client.post("/api/items", json=payload)

    @task(1)
    def config(self):
        self.client.get("/config")
